name: Node.js CI

on: [push, pull_request]

timeout-minutes: 360 # Set the maximum job timeout to 6 hours

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm install telegram-bot-api
      - run: npm install googleapis
      - run: npm run build --if-present
      - run: npm start
      env:
        CI: true

    strategy:
      matrix:
        node-version: [18.x]